## Heart Attack

In [4]:
!pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.8/165.8 kB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.1/486.1 kB 20.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/21.8 MB 71.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 95.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 86.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.7/80.7 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 57.2 MB/s eta 0:00:00
   ━━━━

In [1]:
# Importar librerías
import pandas as pd
import numpy as np
import joblib
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from pycaret.classification import setup, compare_models, save_model
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [3]:
# Leer información
df = pd.read_csv("ai-dl.csv")

About this dataset
* Age : Age of the patient
* Sex : Sex of the patient
* exang: exercise induced angina (1 = yes; 0 = no)
* ca: number of major vessels (0-3)
* cp : Chest Pain type
    - Value 1: typical angina
    - Value 2: atypical angina
    - Value 3: non-anginal pain
    - Value 4: asymptomatic
* trtbps : resting blood pressure (in mm Hg)
* chol : cholestoral in mg/dl fetched via BMI sensor
* fbs : (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)
* rest_ecg : resting electrocardiographic results
    - Value 0: normal
    - Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
    - Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria
* thalach : maximum heart rate achieved
* target : 0= less chance of heart attack 1= more chance of heart attack

## 1. Entendimiento del negocio

- Definir objetivo de negocio según lo que usted considere que puede ser de mayor utilidad según los datos elegidos.

- Definir objetivo analítico.


**Definición del objetivo de negocio:**
El objetivo de negocio será reducir el riesgo de ataques cardíacos mediante la implementación de un sistema que permita identificar oportunamente a pacientes con mayor probabilidad de sufrir un ataque cardíaco. Esto permitirá priorizar la atención médica, optimizar recursos hospitalarios y mejorar la calidad de vida de los pacientes mediante intervenciones tempranas.

**Extensión del objetivo analítico:**
En la metodología CRISP-DM (Cross Industry Standard Process for Data Mining), el objetivo analítico se centra en minimizar los falsos negativos, es decir, los casos en los que se clasifica erróneamente a un paciente en la categoría de "sin riesgo de ataque cardíaco" cuando realmente está en riesgo. Esto se logra haciendo un enfoque en la métrica de Recall.

**Razón de la elección:**

En un contexto médico, un falso negativo tiene implicaciones críticas, ya que significa no identificar a una persona que necesita intervención médica, lo cual puede resultar en consecuencias fatales. Por ejemplo, un paciente no tratado a tiempo podría sufrir complicaciones graves o incluso fallecer.

Al priorizar Recall, se asegura que el modelo sea capaz de identificar la mayor cantidad posible de pacientes en riesgo, aunque ello implique generar más falsos positivos. En este caso, es preferible clasificar a un paciente como "en riesgo" (aunque no lo esté) que dejar de atender a alguien que realmente necesita atención urgente.

**Beneficios del enfoque:**

- Garantiza una mayor cobertura de pacientes en riesgo, reduciendo la probabilidad de casos no detectados.
- Aumenta la confianza en el sistema como herramienta complementaria para los profesionales de la salud.
- Se alinea con la misión de salvar vidas y mejorar los servicios de salud, que son objetivos esenciales en cualquier contexto médico.

In [ ]:
df.describe()

age         sex          cp      trtbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg    thalachh        exng     oldpeak         slp         caa  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

            thall      output  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

No hay valores nulos en d

In [ ]:
df.shape

(303, 14)

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

## 2. Preparación datos

Transformaciones más comunes en esta etapa
- Encoding de variables categóricas (OHE): Es una técnica que transforma variables categóricas en representaciones numéricas para que los algoritmos de machine learning puedan procesarlas, ya que la mayoría no trabajan directamente con texto o categorías.
- Escalado de variables numéricas: Es el proceso de normalizar o estandarizar las variables numéricas para garantizar que todas estén en una misma escala, evitando que algunas dominen el entrenamiento del modelo debido a su rango de valores.
- Balanceo de clases (No aplica): Es el proceso de ajustar la proporción de clases en el conjunto de datos, particularmente cuando hay una desbalanceo significativo entre las clases (por ejemplo, 90% clase 0 y 10% clase 1).

In [ ]:
# Revisar datos nulos
df.isna().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [ ]:
# Revisar balanceo de clases
df.output.value_counts()

output
1    165
0    138
Name: count, dtype: int64

In [ ]:
# OHE sobre variables de naturaleza categórica
variables_naturaleza_categorica = ['cp','restecg','thall','slp']
df = pd.get_dummies(df, columns=variables_naturaleza_categorica, drop_first=True)

## 3. Modelación

### **Pycaret**

In [ ]:
clf_setup = setup(
    data=df,
    target='output',
    preprocess=True,
    train_size = 0.9,  # Entrenar el modelo con el 90% de los datos, ya que en son pocos
    normalize=True
)

best_model = compare_models(sort='Accuracy')

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

### **Búsqueda de hiperparámetros con Gridsearch sobre los mejores modelos arrojados por PyCaret**

In [ ]:
X = df.drop('output', axis=1)
y = df['output']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [ ]:
from sklearn.linear_model import RidgeClassifier

param_grid = {
    'alpha': [0.1, 1, 10],
    'max_iter':[None, 10],
    'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sag', 'saga']
}

# Configuración de GridSearchCV para RidgeClassifier
grid_search = GridSearchCV(RidgeClassifier(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Mejor combinación de hiperparámetros
print('Best Parameters:', grid_search.best_params_)
print('Best Cross-Validation Accuracy:', grid_search.best_score_)

# Modelo con los mejores parámetros
ridge_model = grid_search.best_estimator_
ridge_model.fit(X_train, y_train)

# Evaluación en el conjunto de prueba
y_pred = ridge_model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

Best Parameters: {'alpha': 0.1, 'max_iter': None, 'solver': 'lsqr'}
Best Cross-Validation Accuracy: 0.8383164983164983
Accuracy: 0.7419354838709677
Confusion Matrix:
 [[ 8  6]
 [ 2 15]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.57      0.67        14
           1       0.71      0.88      0.79        17

    accuracy                           0.74        31
   macro avg       0.76      0.73      0.73        31
weighted avg       0.75      0.74      0.73        31



In [ ]:
# Linear Discriminant Analysis

param_grid_lda = {
    'solver': ['svd', 'lsqr', 'eigen'],
    'shrinkage': [None, 'auto'],
    'tol':[0.001,0.0001]
}

# Configuración de GridSearchCV para LDA
grid_search_lda = GridSearchCV(LinearDiscriminantAnalysis(), param_grid_lda, cv=5)
grid_search_lda.fit(X_train, y_train)

# Mejor combinación de hiperparámetros
print('LDA Best Parameters:', grid_search_lda.best_params_)
print('LDA Best Cross-Validation Accuracy:', grid_search_lda.best_score_)

# Modelo con los mejores parámetros
lda_model = grid_search_lda.best_estimator_
lda_model.fit(X_train, y_train)

# Evaluación en el conjunto de prueba
y_pred_lda = lda_model.predict(X_test)
print('LDA Accuracy:', accuracy_score(y_test, y_pred_lda))
print('LDA Confusion Matrix:\n', confusion_matrix(y_test, y_pred_lda))
print('LDA Classification Report:\n', classification_report(y_test, y_pred_lda))

LDA Best Parameters: {'shrinkage': None, 'solver': 'svd', 'tol': 0.001}
LDA Best Cross-Validation Accuracy: 0.8346801346801346
LDA Accuracy: 0.7419354838709677
LDA Confusion Matrix:
 [[ 8  6]
 [ 2 15]]
LDA Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.57      0.67        14
           1       0.71      0.88      0.79        17

    accuracy                           0.74        31
   macro avg       0.76      0.73      0.73        31
weighted avg       0.75      0.74      0.73        31



In [ ]:
from sklearn.naive_bayes import GaussianNB

param_grid_nb = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6]
}

# Configuración de GridSearchCV para GaussianNB
grid_search_nb = GridSearchCV(GaussianNB(), param_grid_nb, cv=5)
grid_search_nb.fit(X_train, y_train)

# Mejor combinación de hiperparámetros
print('Naive Bayes Best Parameters:', grid_search_nb.best_params_)
print('Naive Bayes Best Cross-Validation Accuracy:', grid_search_nb.best_score_)

# Modelo con los mejores parámetros
nb_model = grid_search_nb.best_estimator_
nb_model.fit(X_train, y_train)

# Evaluación en el conjunto de prueba
y_pred_nb = nb_model.predict(X_test)
print('Naive Bayes Accuracy:', accuracy_score(y_test, y_pred_nb))
print('Naive Bayes Confusion Matrix:\n', confusion_matrix(y_test, y_pred_nb))
print('Naive Bayes Classification Report:\n', classification_report(y_test, y_pred_nb))

Naive Bayes Best Parameters: {'var_smoothing': 1e-07}
Naive Bayes Best Cross-Validation Accuracy: 0.8346127946127947
Naive Bayes Accuracy: 0.7419354838709677
Naive Bayes Confusion Matrix:
 [[ 9  5]
 [ 3 14]]
Naive Bayes Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.64      0.69        14
           1       0.74      0.82      0.78        17

    accuracy                           0.74        31
   macro avg       0.74      0.73      0.74        31
weighted avg       0.74      0.74      0.74        31



In [ ]:
from sklearn.linear_model import LogisticRegression

param_grid_lr = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'C': [0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga','lbfgs'],
    'l1_ratio': [None,0.1, 0.5, 0.9],
    'max_iter': [None,100, 500, 1000]
}


grid_search_lr = GridSearchCV(
    LogisticRegression(),
    param_grid_lr,
    cv=5,
    scoring='recall',
    n_jobs=-1,
    verbose=1
)

grid_search_lr.fit(X_train, y_train)

# Mejor combinación de hiperparámetros
print('Logistic Regression Best Parameters:', grid_search_lr.best_params_)
print('Logistic Regression Best Cross-Validation Accuracy:', grid_search_lr.best_score_)

# Modelo con los mejores parámetros
lr_model = grid_search_lr.best_estimator_
lr_model.fit(X_train, y_train)

# Evaluación en el conjunto de prueba
y_pred_lr = lr_model.predict(X_test)
print('Logistic Regression Accuracy:', accuracy_score(y_test, y_pred_lr))
print('Logistic Regression Confusion Matrix:\n', confusion_matrix(y_test, y_pred_lr))
print('Logistic Regression Classification Report:\n', classification_report(y_test, y_pred_lr))

Fitting 5 folds for each of 768 candidates, totalling 3840 fits
Logistic Regression Best Parameters: {'C': 100, 'l1_ratio': None, 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}
Logistic Regression Best Cross-Validation Accuracy: 0.8493602693602693
Logistic Regression Accuracy: 0.7419354838709677
Logistic Regression Confusion Matrix:
 [[ 8  6]
 [ 2 15]]
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.57      0.67        14
           1       0.71      0.88      0.79        17

    accuracy                           0.74        31
   macro avg       0.76      0.73      0.73        31
weighted avg       0.75      0.74      0.73        31



In [ ]:
# LGBM Classifier

param_grid_lgbm = {
    'num_leaves': [31, 50, 70],
    'learning_rate': [0.01, 0.05, 0.1],
    'n_estimators': [50, 100, 200],
    'max_depth': [-1, 10, 20],
}

lgbm = LGBMClassifier(verbosity=-1)

# Configuración de GridSearchCV para LightGBM
grid_search_lgbm = GridSearchCV(lgbm, param_grid_lgbm, cv=5)
grid_search_lgbm.fit(X_train, y_train)

# Mejor combinación de hiperparámetros
print('LightGBM Best Parameters:', grid_search_lgbm.best_params_)
print('LightGBM Best Cross-Validation Accuracy:', grid_search_lgbm.best_score_)

# Modelo con los mejores parámetros
lgbm_model = grid_search_lgbm.best_estimator_
lgbm_model.fit(X_train, y_train)

# Evaluación en el conjunto de prueba
y_pred_lgbm = lgbm_model.predict(X_test)
print('LightGBM Accuracy:', accuracy_score(y_test, y_pred_lgbm))
print('LightGBM Confusion Matrix:\n', confusion_matrix(y_test, y_pred_lgbm))
print('LightGBM Classification Report:\n', classification_report(y_test, y_pred_lgbm))

LightGBM Best Parameters: {'learning_rate': 0.05, 'max_depth': -1, 'n_estimators': 50, 'num_leaves': 31}
LightGBM Best Cross-Validation Accuracy: 0.8162962962962963
LightGBM Accuracy: 0.7419354838709677
LightGBM Confusion Matrix:
 [[ 8  6]
 [ 2 15]]
LightGBM Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.57      0.67        14
           1       0.71      0.88      0.79        17

    accuracy                           0.74        31
   macro avg       0.76      0.73      0.73        31
weighted avg       0.75      0.74      0.73        31



### **Mejor modelo**

Vamos a probar ahora el mejor modelo presentado por pycaret **Ridge Classifier** con hiperparametros optimizados

In [ ]:
from pycaret.classification import *
tuned_model = tune_model(best_model, optimize='Recall')

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


##¿Difieren los resultados respecto a lo hecho con Scikit Learn en el taller pasado?

Las métricas en los resultados tienden a diferir un poco desde PyCaret y la búsqueda de hiperparámetros, esto se debe en parte al conjunto de datos de entrenamieto y prueba con que se ejecutan ambos procesos.

Respecto al ejercicio, al obtener un recall cercano a 0.8 en el mejor modelo, consideramos que este no debería ser utilizado en un ambiente productivo, especialmente en un ámbito médico donde las decisiones tienen un impacto crítico en la vida de los pacientes. Un recall de 0.8 implica que, de cada 10 pacientes que realmente están en riesgo de sufrir un ataque cardíaco, el modelo identifica correctamente a 8, pero falla en detectar 2 pacientes en promedio, clasificándolos erróneamente como "sin riesgo". Este nivel de error es inaceptable en un contexto clínico, ya que las consecuencias de ignorar estos casos pueden incluir complicaciones graves de salud, retrasos en el tratamiento, e incluso la muerte.